#!/usr/bin/env bash

function do_del() {
    MOD_NAME=$1

  echo "deinit ${MOD_NAME} "
  # 逆初始化模块，其中{MOD_NAME}为模块目录，执行后可发现模块目录被清空
  git submodule deinit ${MOD_NAME}

  echo "remove ${MOD_NAME} "
  # 删除.gitmodules中记录的模块信息（--cached选项清除.git/modules中的缓存）
  git rm -f --cached ${MOD_NAME}

  rm -rf .git/module/${MOD_NAME}
  rm -rf ${MOD_NAME}

  # 提交更改到代码库，可观察到'.gitmodules'内容发生变更
  git commit -am "Remove a submodule ${MOD_NAME}"
}

function do_add() {
    git submodule add $1 resources/$2
}

do_$1