FROM registry.cn-beijing.aliyuncs.com/aimonvidia/transformers-all

RUN apt-get update && \
    apt-get install -y curl cmake git wget bzip2 build-essential ninja-build g++ && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

RUN git clone https://github.com/Tencent/TurboTransformers --recursive

RUN cd /workspace/TurboTransformers && \
    mkdir build && \
    cd build && \
    cmake .. -DWITH_GPU=OFF && \
    make -j 8 && \
    pip install ./turbo_transformers/python/pypackage/dist/turbo_transformers-0.0.0-cp37-cp37m-linux_x86_64.whl



