#!/usr/bin/env bash

AMBARI_USER=ambari
AMBARI_PASSWORD=bigdata
AMBARI_SERVER_FQDN='CD-SLJF-SZCY-4-2'
AMBARI_DATABASE=ambari

sudo mysql -u root -pbeijing -e "
CREATE USER '${AMBARI_USER}'@'%' IDENTIFIED BY '${AMBARI_PASSWORD}';
GRANT ALL PRIVILEGES ON *.* TO '${AMBARI_USER}'@'%';
CREATE USER '${AMBARI_USER}'@'localhost' IDENTIFIED BY '${AMBARI_PASSWORD}';
GRANT ALL PRIVILEGES ON *.* TO '${AMBARI_USER}'@'localhost';
CREATE USER '${AMBARI_USER}'@'0.0.0.0' IDENTIFIED BY '${AMBARI_PASSWORD}';
GRANT ALL PRIVILEGES ON *.* TO '${AMBARI_USER}'@'0.0.0.0';
CREATE USER '${AMBARI_USER}'@'${AMBARI_SERVER_FQDN}' IDENTIFIED BY '${AMBARI_PASSWORD}';
GRANT ALL PRIVILEGES ON *.* TO '${AMBARI_USER}'@'${AMBARI_SERVER_FQDN}';
FLUSH PRIVILEGES;

CREATE DATABASE ${AMBARI_DATABASE};
USE ${AMBARI_DATABASE};
SOURCE /var/lib/ambari-server/resources/Ambari-DDL-MySQL-CREATE.sql;
"
