FROM --platform=${BUILDPLATFORM} node:20-bookworm-slim 

COPY docker/ /app/docker/

# Install system dependencies required for node-gyp
RUN /app/docker/apt-install.sh build-essential python3 zstd

# # Run the frontend memory monitoring script
# RUN /app/docker/frontend-mem-nag.sh

WORKDIR /app/superset-frontend

RUN --mount=type=bind,source=./superset-frontend/package.json,target=./package.json \
    --mount=type=bind,source=./superset-frontend/package-lock.json,target=./package-lock.json \
    npm ci